{application,infra_service_app,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{infra_service,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[]},
              {licenses,["Apache 2.0"]},
              {links,[]}]}.
